src/project_msit/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import species.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^species/', include(species.urls, namespace='species')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/species/urls.py
from django.conf.urls import url

from species.views import SpeciesListView,SpeciesDetailView

urlpatterns = [
    url(r'^detail/(?P<pk>\d+)$', SpeciesDetailView.as_view(), name='species-detail'),
    # url(r'^detail/(?P<slug>[-\w]+)$', SpeciesDetailView.as_view(), name='species-detail'),
    url(r'^$', SpeciesListView.as_view(), name='species-list'),
]

src/species/models.py
from django.db import models
from project_msit.settings import base
from django_extensions.db.fields import (
	AutoSlugField, CreationDateTimeField, ModificationDateTimeField,
)

class Category(models.Model):
	title = models.CharField(max_length=40,
		help_text="Write which group this animal belongs to, relative to species's class e.g aves for birds")
	description = models.TextField(blank=True)	
	class Meta:
		verbose_name = 'Category'
		verbose_name_plural = 'Categories'
	def __str__(self):
		return self.title	

class Kingdom(models.Model):
	title = models.CharField(max_length=40,
		help_text="The full scientific name of the kingdom in which the taxon is classified. Example: \"Animalia\", \"Plantae\"")
	description = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Kingdom'
		verbose_name_plural = 'Kingdoms'

	def __str__(self):
		return self.title


class Phylum(models.Model):
	title = models.CharField(max_length=40,
		help_text="The full scientific name of the phylum or division in which the taxon is classified.")
	description = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Phylum'
		verbose_name_plural = 'Phyla'

	def __str__(self):
		return self.title

class ClassName(models.Model):
	title = models.CharField(max_length=40,
		help_text="The full scientific name of the class in which the taxon is classified.")
	group_as = models.ForeignKey(Category,related_name='classname',
		blank=True,null=True,verbose_name="Categorize as",
		help_text="term used by many to easily identify this species e.g Aves is to birds, ")
	description = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Class'
		verbose_name_plural = 'Classes'

	def __str__(self):
		return self.title

class Order(models.Model):
	title = models.CharField(max_length=40,
		help_text="The full scientific name of the order in which the taxon is classified.")
	description = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Order'
		verbose_name_plural = 'Orders'

	def __str__(self):
		return self.title

class Family(models.Model):
	title = models.CharField(max_length=40,
		help_text="The full scientific name of the family in which the taxon is classified.")
	description = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Family'
		verbose_name_plural = 'Families'

	def __str__(self):
		return self.title

class Genus(models.Model):
	title = models.CharField(max_length=40,
		help_text="The full scientific name of the genus in which the taxon is classified")
	description = models.TextField(blank=True)

	class Meta:
		verbose_name = 'Genus'
		verbose_name_plural = 'Genera'


	def __str__(self):
		return self.title

class Species(models.Model):
	RECORD_BASIS = (
		('','-----------'),
		('hob','Human Observation'),
		('lis','Living Speciment'),
		('prs','Preserved Specimen'),
		('fos','Fossil Specimen'),
		('mob','Machine Observation'),
	)

	kingdom = models.ForeignKey(Kingdom,
		help_text="The full scientific name of the kingdom in which the taxon is classified. Example: \"Animalia\", \"Plantae\"")
	phylum = models.ForeignKey(Phylum,
		help_text="The full scientific name of the phylum or division in which the taxon is classified.")
	classname = models.ForeignKey(ClassName, related_name='class_category',
		help_text="The full scientific name of the class in which the taxon is classified.",
		verbose_name="class")
	order = models.ForeignKey(Order,
		help_text="The full scientific name of the order in which the taxon is classified.")
	family = models.ForeignKey(Family,
		help_text="The full scientific name of the family in which the taxon is classified.")
	genus = models.ForeignKey(Genus,
		help_text="The full scientific name of the genus in which the taxon is classified")
	specie = models.CharField(max_length=80,verbose_name="Species",
		help_text="Species name of this species, ex. Familiaris, from Canis Familiaris.")
	sciname_author = models.CharField(max_length=80,verbose_name="Scientific name author")
	basis_of_record = models.CharField(max_length=3,verbose_name="record basis",
		choices=RECORD_BASIS,default='hob',
		help_text="The specific nature of the data record - a subtype of the dcterms:type. ")
	slug = AutoSlugField(populate_from=['genus','specie'],verbose_name="Name")
	taxonomic_notes = models.TextField(help_text="Any notes you wan to add about this species",blank=True)
	profile_pic = models.ImageField('Species Profile Pic',
		upload_to='specie_profile_pics/%Y-%m-%d/', 
		null=True,blank=True)
	created_by = models.ForeignKey(base.AUTH_USER_MODEL,
		null=True, blank=True, 
		on_delete=models.SET_NULL)	

	created = CreationDateTimeField()
	modified = ModificationDateTimeField()

	class Meta:
		verbose_name = 'species'
		verbose_name_plural = 'species'


	def __str__(self):
		return self.get_full_name()

	@property
	def scientific_name(self):
		return self.get_full_name()


	def get_full_name(self):
		return self.genus.title+' '+self.specie

	def save(self, *args, **kwargs):
		# import pdb; pdb.set_trace()
		# x = 1+1
		super().save(*args, **kwargs)


class CommonName(models.Model):
	name = models.CharField(max_length=80)
	species = models.ForeignKey(Species, related_name='common_name', on_delete=models.CASCADE)
	created = CreationDateTimeField()
	modified = ModificationDateTimeField()

	def __str__(self):
		return self.name

class SpeciesImage(models.Model):
	species = models.ForeignKey(Species, related_name='specie_image',help_text="Add your species image(s) here")
	pic = models.ImageField('Species Image',upload_to='species_pics/%Y-%m-%d/',null=True,blank=True)
	description = models.TextField(blank=True,help_text="Any description of the image e.g attribution, location etc.")

	def image_tag(self):
		
		return u'<img src="%s" width="100" height="100"/>' % self.pic.url

	image_tag.short_description = "Image"
	image_tag.allow_tags = True

	def __str__(self):
		return self.species.scientific_name

src/species/forms.py
# from __future__ import unicode_literals
# from django.contrib.auth.forms import AuthenticationForm
# from django import forms
# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
# from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
# from authtools import forms as authtoolsforms
# from django.contrib.auth import forms as authforms
# from django.core.urlresolvers import reverse


# class LoginForm(forms.form):
#     remember_me = forms.BooleanField(required=False, initial=False)

#     def __init__(self, *args, **kwargs):
#         super(LoginForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.fields["username"].widget.input_type = "email"  # ugly hack

#         self.helper.layout = Layout(
#             Field('username', placeholder="Enter Email", autofocus=""),
#             Field('password', placeholder="Enter Password"),
#             HTML('<a href="{}">Forgot Password?</a>'.format(
#                 reverse("accounts:password-reset"))),
#             Field('remember_me'),
#             Submit('sign_in', 'Log in',
#                    css_class="btn btn-lg btn-primary btn-block"),
#             )


# class SignupForm(authtoolsforms.UserCreationForm):

#     def __init__(self, *args, **kwargs):
#         super(SignupForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.fields["email"].widget.input_type = "email"  # ugly hack

#         self.helper.layout = Layout(
#             Field('email', placeholder="Enter Email", autofocus=""),
#             Field('name', placeholder="Enter Full Name"),
#             Field('password1', placeholder="Enter Password"),
#             Field('password2', placeholder="Re-enter Password"),
#             Submit('sign_up', 'Sign up', css_class="btn-warning"),
#             )


# class PasswordChangeForm(authforms.PasswordChangeForm):

#     def __init__(self, *args, **kwargs):
#         super(PasswordChangeForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()

#         self.helper.layout = Layout(
#             Field('old_password', placeholder="Enter old password",
#                   autofocus=""),
#             Field('new_password1', placeholder="Enter new password"),
#             Field('new_password2', placeholder="Enter new password (again)"),
#             Submit('pass_change', 'Change Password', css_class="btn-warning"),
#             )


# class PasswordResetForm(authtoolsforms.FriendlyPasswordResetForm):

#     def __init__(self, *args, **kwargs):
#         super(PasswordResetForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()

#         self.helper.layout = Layout(
#             Field('email', placeholder="Enter email",
#                   autofocus=""),
#             Submit('pass_reset', 'Reset Password', css_class="btn-warning"),
#             )


# class SetPasswordForm(authforms.SetPasswordForm):
#     def __init__(self, *args, **kwargs):
#         super(SetPasswordForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()

#         self.helper.layout = Layout(
#             Field('new_password1', placeholder="Enter new password",
#                   autofocus=""),
#             Field('new_password2', placeholder="Enter new password (again)"),
#             Submit('pass_change', 'Change Password', css_class="btn-warning"),
#             )

src/species/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.db.models import Q
from project_msit.settings import base

from species.models import Species,Category,SpeciesImage

class SpeciesListView(ListView):
	model = Species 
	queryset = Species.objects.select_related('classname__group_as',
		'kingdom','phylum','order','family','genus','created_by').all().order_by('-modified')		
	template_name = 'species/list_species.html'
	paginate_by=4


	def get_queryset(self):
		'''
			we simply override the queryset, and get the default queryset(that one above), 
			and filter it according to parameters from users
			we use Q object for this
		'''
		qs = super(SpeciesListView, self).get_queryset()
		user_query = self.request.GET.get("q")
		user_filter = self.request.GET.get("search_param")
		# import pdb; pdb.set_trace()
		if user_query:
			user_query=user_query.strip()
			return qs.filter(
				Q(kingdom__title__icontains=user_query) |
				Q(phylum__title__icontains=user_query) |
				Q(order__title__icontains=user_query) |
				Q(family__title__icontains=user_query) |
				Q(genus__title__icontains=user_query) |
				Q(specie__icontains=user_query) |
				Q(sciname_author__icontains=user_query) |
				Q(classname__group_as__title__icontains=user_query) |
				Q(created_by__name__icontains=user_query) 
			)
		return qs 

	def get_context_data(self, **kwargs):
		context = super(SpeciesListView, self).get_context_data(**kwargs)
		# context['now'] = timezone.now()
		# use annotation here, some duplicate query detected
		context['category_list'] = Category.objects.all()
		return context

class SpeciesDetailView(DetailView):
	model = Species 
	context_object_name = 'specie_detail'
	template_name = 'species/detailview.html'
	# slug_field = 'slug'

	def get_queryset(self):
		#import pdb; pdb.set_trace()
		if 'pk' in self.kwargs:
			return Species.objects.select_related('classname__group_as','kingdom',
				'phylum','order','family','genus','created_by').filter(id=self.kwargs['pk'])
		return None		

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		# context['now'] = timezone.now()
		context['category_list'] = Category.objects.all().order_by('title')
		spqs = SpeciesImage.objects.filter(species__id=self.kwargs['pk'])
		context['image_urls'] = [s.pic.url for s in spqs]
		# import pdb; pdb.set_trace()
		return context	

src/species/templates/species/list_species.html
{% extends "base.html" %} 
{% load staticfiles %} 
{% load thumbnail %}
{% block title %}{{ block.super }}Species{% endblock %} 
{% block navbar-left %} 
{% include "_navbar.html" with active_link="species" %} 
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
<div id="searchpage" class="text-page2">
    <div class="container">
        <div class="row">
        </div>

        <div class="row">
            <div id="sidebarsection" class="col-sm-2">
                <div class="row"></div>
                <div class="row">
                    <nav id="cats" class="nav-sidebar">
                        <ul class="nav">
                            <li><a href="{% url "species:species-list" %}?q=">All</a></li>
                            {% for category in category_list %}
                                <li><a href="{% url "species:species-list" %}?q={{category.title}}">{{category.title}}</a></li>
                            {% endfor %}
                            <li class="nav-divider"></li>
                            <li><a href="#"><i class="glyphicon glyphicon-off"></i> Export</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div id="searchsection" class="col-md-10 text-center">
                <form method='GET' action=''>
                <div class="row">
                    <div class="col-sm-12">
                        <h2>Search for Species</h2>
                        <p class="lead">searching leads to power</p>
                        <div class="input-group">
                            <div class="input-group-btn search-panel">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <span id="search_concept">Filter by</span> <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#contains">Contains</a></li>
                                    <li><a href="#its_equal">It's equal</a></li>
                                    <li><a href="#greather_than">Greather than &gt;</a></li>
                                    <li><a href="#less_than">Less than &lt; </a></li>
                                    <li class="divider"></li>
                                    <li><a href="#all">Anything</a></li>
                                </ul>
                            </div>
                            <input type="hidden" name="search_param" value="all" id="search_param">
                            <input type="text" class="form-control" value="{{request.GET.q}}" name="q" placeholder="Search term...">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                            </span>
                        </div>
                    </div>
                </div>
                </form>
                <div id="displayspec" class="row">
                    {% for specie in species_list %}
                    <div class="row">
                        <div class="col-sm-2">
                            
                    <img title="Species Photo" class="img-circle img-responsive" src="{% thumbnail specie.profile_pic|default:'species_profile.png' 170x170 crop%}">
                        </div>
                        <div class="col-sm-10 text-left">
                            <h2><a href="{% url 'species:species-detail' specie.pk %}">{{specie.scientific_name |capfirst}},{{specie.sciname_author}} </a></h2>
                            <strong>Discovered by : </strong><i>{{specie.sciname_author}}</i>
                            <br>
                            <strong>Genus : </strong><i>{{specie.genus}}</i>
                            <br>
                            <strong>Species Name : </strong><i>{{specie.specie}}</i>
                            <br>
                            <strong>Slug : </strong><i>{{specie.slug}}</i>
                            <br>
                            <strong>Basis of Record : </strong><i>{{specie.basis_of_record}}</i>
                            <br>
                            <strong>Taxonomic Notes : </strong>
                            <br>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi soluta praesentium nostrum, aliquam eos voluptate eaque laboriosam aliquid sed, quas quidem voluptatem nulla quisquam odit qui aspernatur, quo blanditiis. Repellat.</p>
                            <strong>Researcher : </strong><i>{{specie.created_by}}</i>
                            <br>
                            <strong>Last Modified : </strong><i>{{specie.modified | date:"D d M Y"}}</i>
                            <hr>
                        </div>
                        <br>
                        <br>
                    </div>
                    {% endfor %}
                </div>
            {% if is_paginated %}
                <div class="row">
                        <nav id="pagination-setting" aria-label="Page navigation example">
                            <div class="col-md-2">
                            </div>
                            <div class="col-md-10">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h3 class="text-left">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</h3>
                                    </div>
                                    <div class="col-md-6">
                                        <ul class="pagination text-right">
                                          {% if page_obj.has_previous %}
                                            <li class="page-item"><a class="page-link" href="/species?page={{page_obj.previous_page_number}}">Previous</a></li>
                                          {% endif %}


                                          {% for page in page_obj.paginator.page_range %}
                                                {% if page_obj.number == page %} 
                                                    <li class="active">
                                                        <a href="/species?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
                                                    </li> 
                                                {% else %}
                                                    <li>
                                                        <a href="/species?page={{page}}">{{page}}</a>
                                                    </li> 
                                                {% endif %}
                                          {% endfor %}
                   
                                          {% if page_obj.has_next %}
                                            <li class="page-item"><a class="page-link" href="/species?page={{page_obj.next_page_number}}">Next</a></li>
                                          {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </nav>
                </div>
            {% endif %}
            </div>
        </div>

    </div>
</div>
<div id="sec3">
    <div class="container">
        <div class="row">
            <div id="map-outer" class="col-md-12">
                <div id="address" class="col-md-4">

                </div>
                <div id="map-container" class="col-md-8"></div>
            </div>
        </div>
    </div>
</div>
{% endblock container %} 
{% block scripts %}
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script>

    $(document).ready(function(e) {
        //https://stackoverflow.com/questions/5448545/how-to-retrieve-get-parameters-from-javascript
        function getSearchParameters() {
              var prmstr = window.location.search.substr(1);
              return prmstr != null && prmstr != "" ? transformToAssocArray(prmstr) : {};
        }

        function transformToAssocArray( prmstr ) {
            var params = {};
            var prmarr = prmstr.split("&");
            for ( var i = 0; i < prmarr.length; i++) {
                var tmparr = prmarr[i].split("=");
                params[tmparr[0]] = tmparr[1];
            }
            return params;
        }     

        var params = getSearchParameters();
        var s = decodeURIComponent(params.q);
       
        if(s=='undefined' || s=="") s='All';
        $('nav#cats > ul > li:contains('+s+')')
            .addClass('active')
            .siblings()
            .removeClass('active');

        $('.search-panel .dropdown-menu').find('a').click(function(e) {
            e.preventDefault();
            var param = $(this).attr("href").replace("#", "");
            var concept = $(this).text();
            $('.search-panel span#search_concept').text(concept);
            $('.input-group #search_param').val(param);
        });

    }); //document ready
</script>

{% endblock scripts %}

src/species/templates/species/listview.html
{% extends "list_species.html" %} 

{% block display_species %}
  <h1>List View</h1>
  <div id="displayspec" class="row" >
     {% for specie in species_list %}
     <div class="row">
        <div class="col-sm-2">
          <h2>picture</h2>
        </div>
        <div class="col-sm-10 text-left">
          <h1><a href="#">{{specie.scientific_name}}</a></h1>
          <strong>Kingdom : </strong><i>{{specie.kingdom}}</i><br>
          <strong>Phylum : </strong><i>{{specie.phylum}}</i><br>
          <strong>Class : </strong><i>{{specie.classname}}</i><br>
          <strong>Order : </strong><i>{{specie.order}}</i><br>
          <strong>Family : </strong><i>{{specie.family}}</i><br>
          <strong>Genus : </strong><i>{{specie.genus}}</i><br>
          <strong>Species Name : </strong><i>{{specie.specie}}</i><br>
          <strong>Slug : </strong><i>{{specie.slug}}</i><br>
          <strong>Scientific Name Author : </strong><i>{{specie.sciname_author}}</i><br>
          <strong>Basis of Record : </strong><i>{{specie.basis_of_record}}</i><br>
          <strong>Taxonomic Notes : </strong><br>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi soluta praesentium nostrum, aliquam eos voluptate eaque laboriosam aliquid sed, quas quidem voluptatem nulla quisquam odit qui aspernatur, quo blanditiis. Repellat.</p>
          <strong>Researcher : </strong><i>{{specie.created_by}}</i><br>
          <strong>{{now}}</strong><br>
        </div>
        <br>
        <br>
        <br>
        <br>
      </div>
     {% endfor %}
  </div>
{% endblock display_species %}  